site_name: Mi Portafolio
theme:
  name: material
  language: es
  footer: false

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexander-motoche-208510327/
    - icon: fontawesome/brands/github
      link: https://github.com/XLex0
  copyright: "© 2025 Mi Portafolio | Desarrollado por Alexander Motoche"
